name: Cron Job
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call URL
        run: |
          for i in 1 2 3 4 5; do
            curl -s "https://aitrend.great-site.net/cron_thoisu.php"
            sleep 60
          done
